version: '3.8'

services:

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27019:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

  spider_backend:
    container_name: spider_backend
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
